name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Configure Git User
        run: |
          git config --global user.email "wasuwat.limsuparhat@refinitiv.com"
          git config --global user.name "wsuwt"


      - run: npm ci --ignore-scripts --audit=false --fund=false

      
      - name: Tag version and create GitHub release
        run: lerna version --create-release github --conventional-commits --loglevel silly --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}