name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm ci --ignore-scripts --audit=false --fund=false
      - run: lerna run build:prod --include-dependencies --since
      - run: lerna version --conventional-commits --create-release github --yes